 language: java
jdk: oraclejdk8
cache:
  directories:
- $HOME/.m2
install:
- echo "install nothing!"
script:
- "./mvnw clean install -B -V"
- bash <(curl -s https://codecov.io/bash) -t repository-upload-token
before_install:
- chmod +x ./mvnw