 language: java
jdk: oraclejdk8
before_install:
  - chmod +x mvnw
git update-index --chmod=+x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- bash <(curl -s https://codecov.io/bash) -t repository-upload-token
cache:
  directories:
- $HOME/.m2