 language: java
jdk: oraclejdk8
cache:
  directories:
- $HOME/.m2
install:
- mvn -N io.takari:maven:wrapper
script:
- "./mvnw clean install -B -V"
- bash <(curl -s https://codecov.io/bash) -t repository-upload-token
before_install:
- chmod +x ./mvnw